### ISSUE TITLE
Collection created from gallery showing moderation status link

### ISSUE THREAD

**Issue by SatejG** [gnowledge/gstudio#1549]
Collection created from gallery showing moderation status to check, But its automatically gets moderated and successfuly published, then we may not required moderation step.

**Comment by saavrabh** [comment]
@SatejG  please check moderation policy of that course group.

**Comment by katkamrachana** [comment]
@SatejG please update this issue.

**Comment by katkamrachana** [comment]
Files will go for moderation where for Moderation applied Groups.
If the type is of Moderation Group, but the moderation level is set to 0(zero), it will be uploaded without any moderation required.
This issue is closed due to no update from the author. Please re-open if more clarification is needed.
