### ISSUE TITLE
Activity 3.3: Image is broken

### ISSUE THREAD

**Issue by TanviB25** [gnowledge/gstudio#1601]
Reference: http://103.36.84.136/invitation2clix/file/readDoc/575671ae2e013103e395d609/sample-object-charts-collage.png

With reference to above url, I have found image is broken, unable to view and download.

![activity3 3](https://cloud.githubusercontent.com/assets/19238176/22396249/469b7a6a-e57a-11e6-88f5-bdb73a79e4b6.png)
![img broken_can t_view_download](https://cloud.githubusercontent.com/assets/19238176/22396250/469bd1cc-e57a-11e6-9d19-d6ac8ae8133a.png)

**Comment by udnshah** [comment]
@TanviB25 

This is a content (data) related bug. You can report such bugs by separate email to Amit.

Only the code related bugs and error should be reported in github

So this image is corrupted hence it has to be replaced in the data(in the installer)

Thank you

**Comment by mrunal4** [comment]
This issue is also resolved by clearing the disk space. Kindly visit below links to verify the same.

### Page link:
```
http://103.36.84.136/invitation2clix-hindi/gcourse/course_section/57927193a6127d01f8e869ed/57927193a6127d01f8e869ef/57927193a6127d01f8e869f1/
```

### Image link:
```
http://103.36.84.136/invitation2clix/file/readDoc/575671ae2e013103e395d609/sample-object-charts-collage.png
```

Kindly close this issue, or guide me how to do the same.

### Troubleshooting and solution:
This issue must be because of insufficient disk space for some operations related to image displaying (disk space for the drive was full). I had removed <container-id>-json.log for gstudio container as it was consuming almost 53GB after stopping the container. Once it is cleared I restarted the container with `docker start gstudio`. Exact command to remove the file was:
```
rm /var/lib/docker/containers/b50ce887742d943e47993192b2b6302db434679423b47c3ded33282421d55f55/b50ce887742d943e47993192b2b6302db434679423b47c3ded33282421d55f55-json.log
```

**Comment by katkamrachana** [comment]
Thanks @mrunal4
